Develop/lcsec
3Pi1416/IFT3913-A-A22-TP1 pull request #3
Opened 2022-09-17 21:05 UTC by mvr-2

2022-09-17 21:54 UTC, 3Pi1416 requested changes

2022-09-17 21:54 UTC, 3Pi1416 commented on src/lcsec.py
> +def lcsec(path_folder: str, csv_file: Path):
```suggestion
def lcsec(path_folder: Path, csv_file: Path):
```

2022-09-17 21:54 UTC, 3Pi1416 commented on src/lcsec.py
> +    absolute_path = path_folder + file_path[1:]
```suggestion
    absolute_path = Path.joinpath(path_folder, file_path)
```

2022-09-17 21:54 UTC, 3Pi1416 commented on src/lcsec.py
> +def mentions(path_folder: str, file_path: str, class_name: str):
```suggestion
def mentions(path_folder: Path, file_path: Path, class_name: str):
```

2022-09-17 21:54 UTC, 3Pi1416 commented on src/lcsec.py
> +            if line[0] != '/' and line[1] != '/':
```suggestion
            if line[0] != '/' or line[1] != '/':
```

ou if not( line[0] == '/' and line[1] == '/' ) :

2022-09-17 21:54 UTC, 3Pi1416 commented on src/lcsec.py
> +    if not csv_file.is_file:
```suggestion
    if not csv_file.is_file():
```

2022-09-17 21:54 UTC, 3Pi1416 commented on src/lcsec.py
> +        print(",".join(row))
Juste pour être sur, ca fonctionne bien, avec les saut de ligne et tout ?

2022-09-17 22:09 UTC, mvr-2 commented on src/lcsec.py
> +        print(",".join(row))
oui!

2022-09-18 15:46 UTC, 3Pi1416 approved these changes

2022-09-18 15:53 UTC, merged